### ISSUE TITLE
Publication languange in News Sitemap (TYPO3 6.2)

### ISSUE THREAD

**Issue by lucasinteractive** [dmitryd/typo3-dd_googlesitemap#55]
I've upgraded TYPO3 from 4.7. to 6.2. The publication language now is empty. I checked the source (7Renderers/NewsSitemapRenderer.php:renderEntry()) an found: ```$GLOBALS['TSFE']->lang```. But i don't know how this is to set. 

My ts setup looks like this:

    config {
        linkVars = L
        sys_language_uid = 0
        language = de
        locale_all = de_DE
        htmlTag_langKey = de
    }

But this seems not to recognized by TSFE->lang. Any suggestions?

**Comment by dmitryd** [comment]
Please, ask for suggestions in TYPO3 mailing list. This place is for bugs.

**Comment by lucasinteractive** [comment]
Does this mean that you are sure this is not a bug in your extension and ```$GLOBALS['TSFE']->lang``` is the working way of getting sites language in T3 6.2.?

**Comment by dmitryd** [comment]
http://catb.org/~esr/faqs/smart-questions.html#idp64670560 and http://catb.org/~esr/faqs/smart-questions.html#uselists

In short: if you report something in the bug tracker, it is your responsibility to make absolutely sure it is a bug. Otherwise you force me to spend my own free time on something that could be a local problem.

Remember, this is free work. And it is my time you are requesting to spend for free. What if it is not a bug? Who will reimburse this uselessly spent time?

**Comment by lucasinteractive** [comment]
Sorry for wasting you own free time. Here a some more detailed analysis:

```$GLOBALS['TSFE']->lang``` is inizialized in ```TypoScriptFrontendController->initLLvars()```. This will called in bootstrapping process at ```ìndex_ts.php``` by ```$TypoScriptFrontendController->settingLanguage()```. Because the extension use eID this sequence is skipped. 

An equal boot process in this extension is handled by ```EtryPoint->initTSFE()```. Adding ```$tsfe->settingLanguage();``` in it will init ```$GLOBALS['TSFE']->lang```. Then the correct news publication language will shown in the news sitemap.

**Comment by dmitryd** [comment]
Thank you for analysis. I will try to reproduce the issue and fix it.
