### ISSUE TITLE
7 LTS support

### ISSUE THREAD

**Issue by DenisMir** [dmitryd/typo3-dd_googlesitemap#60]
It would be great if the dependencies could be updated to support 7 LTS (7.6.0).

**Comment by mansoorahmadhh** [comment]
Hello,

On TYPO3 7.4.0 was the Version v2.0.4 working fine, but since LTS of 7.6.X if i try to open the sitemap xml via www.mydomain.de/home.html?eID=dd_googlesitemap then i get this Errormessage:

"No class named DmitryDulepov\DdGooglesitemap\Generator\PagesSitemapGenerator"

Thanks for fixing.

With best regards,
Mansoor Ahmad

Link: https://github.com/typo3-ter/dd_googlesitemap/issues/1

**Comment by dmitryd** [comment]
Fixed [here](https://github.com/dmitryd/typo3-dd_googlesitemap/commit/7368c41d922a7f304106cac8e79c3155648beaf6).
